---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.4
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.25
    hooks:
      - id: uv-lock
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2026.06.26
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.1.3
    hooks:
      - id: markdown-toc-creator
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.38
    hooks:
      - id: pymarkdown
